[tool.poetry]
name = "cert-transparency-slack"
version = "0.1.0"
description = ""
authors = ["Bruno Alla <bruno.alla@festicket.com>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.18.0"
slackclient = "^2.9.3"
environs = "^9.0.0"
sentry-sdk = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.1"
respx = "^0.16.0"
pytest-mock = "^3.3.1"
pytest-cov = "^2.10.1"
coverage = "^5.4"
flake8 = "^3.8.4"
pyupgrade = "^2.7.3"
isort = "^5.6.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-Wdefault --cov=src"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
ignore_errors = true

[tool.isort]
profile = "black"
