[tool.poetry]
name = "cert-transparency-slack"
version = "0.1.0"
description = ""
authors = ["Bruno Alla <bruno.alla@festicket.com>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.23.0"
slackclient = "^2.9"
environs = "^9.0"
sentry-sdk = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
respx = "^0.20.0"
pytest-mock = "^3.3"
pytest-cov = "^3.0"
coverage = "^6.0"

[tool.pytest.ini_options]
addopts = "-Wdefault --cov=src"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
ignore_errors = true

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
