service: serverless-ct-slack-bot

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  profile: ${opt:profile, ''}
  region: ${opt:region, 'eu-west-2'}

  lambdaHashingVersion: 20201221

  # Optional API Gateway global config
  apiGateway:
    shouldStartNameWithService: true

functions:
  event:
    handler: src.main.event_handler
    events:
      - http: POST /
  verify:
    handler: src.main.verify_handler
    events:
      - http: GET /

plugins:
  - serverless-python-requirements
