name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: "true"
      - run: uv sync --no-python-downloads
      - run: uv run pytest --cov-report=xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    environment: release
    if: github.ref == 'refs/heads/main'
    needs:
      - test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Write .env file
        run: |
          echo "SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL='${{ secrets.SLACK_CHANNEL }}'
          FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}
          DOMAINS_LIST=${{ secrets.DOMAINS_LIST }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}" > .env

      - uses: actions/setup-node@v4
      - run: yarn
      - run: yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
