name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.2
      - name: Install Dependencies
        run: poetry install
      - name: Test with Pytest
        run: poetry run pytest --cov-report=xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.4.1

  lint:
    strategy:
      fail-fast: false
      matrix:
        linter:
          - name: flake8
            run: flake8
          - name: black
            run: black --check .
          - name: pyupgrade
            run: pyupgrade --py38-plus `find . -name "*.py"`
          - name: isort
            run: isort -cv .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.2
      - name: Install Dependencies
        run: poetry install
      - name: ${{ matrix.linter.name }}
        run: poetry run ${{ matrix.linter.run }}

  deploy:
    runs-on: ubuntu-latest
    environment: release
    if: github.ref == 'refs/heads/main'
    needs:
      - test
      - lint

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.2
      - uses: actions/setup-node@v2.1.5
      - run: yarn
      - run: yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}